### ISSUE TITLE
Relocation using g_win32_get_package_installation_directory_of_module?

### ISSUE THREAD

**Issue by manisandro** [rrthomas/enchant#172]
A gather from the source code that the user is expected to call `enchant_set_prefix_dir` for relocation to work correctly. Another approach would be to attempt to automatically detect the prefix on win32 using [g_win32_get_package_installation_directory_of_module](https://developer.gnome.org/glib/stable/glib-Windows-Compatibility-Functions.html#g-win32-get-package-installation-directory-of-module) (while still keeping `enchant_set_prefix_dir` to allow the user to set the prefix explicitly). Would such a patch be accepted?

**Comment by rrthomas** [comment]
Where did you read this please? It seems there is some confusion. In enchant 2.x, relocation is supported by the gnulib relocatable module, which has specific support for working automatically on Windows. I'd like to improve the documentation to avoid this misunderstanding.

This is documented in `INSTALL` and `enchant.h`, so I'd like to know how you got the impression that the user is expected to call `enchant_set_prefix_dir`!

**Comment by manisandro** [comment]
Well I was debugging why my mingw build of enchant2 wasn't picking up any dictionaries, and looking at the source code I (unless mistaken) see the main logic in `lib/relocatable.c`, and the important function there seems to be `set_relocation_prefix` which is called by `enchant_set_prefix_dir` in `src/lib.c`. Nothing calls this function, so I assumed it was the users responsibility to call it.

**Comment by manisandro** [comment]
If it is supposed to work automatically, then something is broken and I need to debug further... ProcessMonitor shows the application searching for the enchant provides in definitely the wrong folder (the drive is the one from which the application is started, but the rest of the path corresponds to the prefix set when compiling). (This is when compiling with `--enable-relocatable`).

**Comment by rrthomas** [comment]
The `INSTALL` file does clearly say:

If Enchant is installed in a fixed location, and on Windows and Linux
systems, no further configuration should be needed to make it relocatable;
that is, work when copied from its original installation directory to
another location.

Otherwise, and in code intended to be portable to other systems, your code
should call enchant_set_prefix_dir (see enchant.h) before any other Enchant
function.

**Comment by manisandro** [comment]
Well it used to work for enchant-1.x, so I'd say win32 should be such a platform. I'll debug further.

**Comment by rrthomas** [comment]
Enchant 1 had custom code to support relocation. In Enchant 2 that has been removed in favour of using gnulib's relocatable module, and relocation works a bit differently.

So far, the documentation seems fairly clear to me (except that you didn't seem to realise that code in `lib` is not part of enchant), but of course if it can be improved, patches are welcome.

**Comment by manisandro** [comment]
The first thing I notice is that the following line in `src/Makefile.am`

    DEFS = -DENABLE_COSTLY_RELOCATABLE -DIN_LIBRARY -DINSTALLDIR=\"$(libdir)\"

sets some defines which are not used by any file in `src`, but they would be used by files in `lib`, but `lib/Makefile.am` does not set these. So `relocatable.c@relocate` does not actually compute the prefix. If I set those defines in `lib/Makefile.am`, `relocatable.c@compute_curr_prefix` is called, but that function errors out here

    277:    if (rp > rel_installdir)
    278:      {
    279:        /* Unexpected: The curr_installdir does not end with rel_installdir.  */
    280:        free (curr_installdir);
    281:        return NULL;
    282:      }

for reasons I haven't yet figgured out, and it is not like the path is something odd, just `C:\Users\Username\Desktop\test`. I'll keep looking.

**Comment by manisandro** [comment]
So there are three issues:
- As mentioned above, the defs are not set in `lib/Makefile.am`
- `INSTALLDIR` needs to be `$(bindir)` on Windows, not `$(libdir)`
- The hunspell provider library does not relocate `ENCHANT_HUNSPELL_DICT_DIR` if it is set

I'd file a PR, but I haven't figured out how `lib` is generated (since it is not in the git tree). FWIW, the patch I applied to the release-tarball contents is

    diff -rupN enchant-2.1.3/lib/Makefile.am enchant-2.1.3-new/lib/Makefile.am
    --- enchant-2.1.3/lib/Makefile.am	2017-09-08 15:42:07.000000000 +0200
    +++ enchant-2.1.3-new/lib/Makefile.am	2017-12-09 15:19:01.879903315 +0100
    @@ -222,6 +222,12 @@ EXTRA_libgnu_la_SOURCES += rawmemchr.c
    ## begin gnulib module relocatable-lib-lgpl
    
    DEFS += -DNO_XMALLOC
    +AM_CPPFLAGS = -I$(top_srcdir) $(ISYSTEM)$(top_builddir)/lib $(ISYSTEM)$(top_srcdir)/lib $(ENCHANT_CFLAGS) $(WARN_CFLAGS)
    +if OS_WIN32
    +DEFS += -DENABLE_COSTLY_RELOCATABLE -DIN_LIBRARY -DINSTALLDIR=\"$(bindir)\"
    +else
    +DEFS += -DENABLE_COSTLY_RELOCATABLE -DIN_LIBRARY -DINSTALLDIR=\"$(libdir)\"
    +endif
    
    EXTRA_DIST += relocatable.c relocatable.h relocatable.valgrind
    
    diff -rupN enchant-2.1.3/providers/enchant_hunspell.cpp enchant-2.1.3-new/providers/enchant_hunspell.cpp
    --- enchant-2.1.3/providers/enchant_hunspell.cpp	2017-09-08 15:32:21.000000000 +0200
    +++ enchant-2.1.3-new/providers/enchant_hunspell.cpp	2017-12-09 15:29:39.934040179 +0100
    @@ -199,7 +199,7 @@ s_buildDictionaryDirs (std::vector<std::
            }
    
    #ifdef ENCHANT_HUNSPELL_DICT_DIR
    -	dirs.push_back (g_strdup (ENCHANT_HUNSPELL_DICT_DIR));
    +	dirs.push_back (enchant_relocate (ENCHANT_HUNSPELL_DICT_DIR));
    #endif
    }
    
    diff -rupN enchant-2.1.3/src/enchant-provider.h enchant-2.1.3-new/src/enchant-provider.h
    --- enchant-2.1.3/src/enchant-provider.h	2017-09-08 15:32:21.000000000 +0200
    +++ enchant-2.1.3-new/src/enchant-provider.h	2017-12-09 15:33:29.086968132 +0100
    @@ -69,6 +69,16 @@ GSList *enchant_get_conf_dirs (void);
    char *enchant_get_prefix_dir(void);
    
    /**
    + * enchant_relocate
    + *
    + * Returns a string giving the relocated path according to the location of the
    + * base directory of the enchant installation.
    + *
    + * Returns: the relocated path. Must be free'd.
    + */
    +char *enchant_relocate (const char *path);
    +
    +/**
    * enchant_dict_set_error
    * @dict: A non-null dictionary
    * @err: A non-null error message
    diff -rupN enchant-2.1.3/src/lib.c enchant-2.1.3-new/src/lib.c
    --- enchant-2.1.3/src/lib.c	2017-11-26 14:56:35.000000000 +0100
    +++ enchant-2.1.3-new/src/lib.c	2017-12-09 15:35:01.264560633 +0100
    @@ -93,7 +93,7 @@ typedef void             (*EnchantPreCon
    /********************************************************************************/
    
    /* Relocate a path and ensure the result is allocated on the heap */
    -static char *
    +char *
    enchant_relocate (const char *path)
    {
        char *newpath = (char *) relocate (path);

**Comment by rrthomas** [comment]
I'm glad you've managed to patch this to your satisfaction, and thanks for sharing. However, unfortunately none of your patches work for Enchant itself:

1. As I said, the relocate module is part of gnulib. I believe it should be compiled each time it is used, and not linked into libgnu (that is why I had `DEFS` set in `src/Makefile.am`). It seems something is wrong; I'll ask upstream about that.
2. Enchant is a library. It therefore should locate its files relative to `libdir`. Changing this to `bindir` looks wrong. Can you explain the logic please, so I can work out what's going on?
3. `ENCHANT_HUNSPELL_DICT_DIR` is meant to be the location of system-installed dictionaries, so it is intentional that it is not relocated. If you are building hunspell as part of a relocatable app, then you shouldn't be using it.

**Comment by manisandro** [comment]
2. The standard layout for win32 is that dlls are bin `bin`, and the `dll.a` import libraries are in `lib`. This layout is also used by autotools.
3. Again from a packaging perspective, this does not really work. To make the mingw example here: you compile the packages using the prefix of the host system (`/usr/x86_64-w64-mingw32/sys-root/mingw/` on Fedora), but you expect the files below that prefix to be relocatable, meaning that to distribute your cross-compiled application, you just take the relevant files below that prefix and deploy them to the windows system. It now happens to be the case that (for historical reasons I suppose) `mingw-enchant` installs its dictionaries to `/usr/x86_64-w64-mingw32/sys-root/mingw/share/myspell`, so this path is passed when compiling enchant. But I still expect the path to be relocated when distributing the application.

**Comment by rrthomas** [comment]
Thanks for the explanation. So:

2. OK, I see. Again, this looks like something I'll have to take to gnulib upstream.
3. There's nothing "historical" going on here, enchant just uses the standard autotools setup. What happens when you build a typical program with no relocation support in this scenario? As far as I can see, the prefix of the host system is a `DESTDIR` setting, and on Windows, mingw has some idea of where its root is, so no relocation needs to be done (because "/" is automatically mapped to the right place in the Windows file system). In any case, clearly on mingwin this is made to work without specific relocation support in individual programs, so there can't be any need for it in Enchant. (In my previous answer, I was talking about the case where you're building a portable/relocatable app, say, Abiword, which contains both Enchant and hunspell.)

**Comment by manisandro** [comment]
("historical" was just to explain why the Fedora mingw-hunspell package installs to `/usr/x86_64-w64-mingw32/sys-root/mingw/share/myspell` and not `/usr/x86_64-w64-mingw32/sys-root/mingw/share/hunspell`, which is the location where enchant looks for the dictionaries by default. But this is just a side note).

The scenario I'm talking about here is cross-compilation and distribution of windows binaries compiled (via mingw-toolchain) on a Linux host. The way it works is as follows:
- On your host (Linux) system, you have regular packages (say `rpm` or `deb` or whatever) containing the cross-compiled libaries (see i.e. [here](https://koji.fedoraproject.org/koji/search?match=glob&type=package&terms=mingw*)). These are installed to some prefix on the host system, on Fedora it is `/usr/x86_64-w64-mingw32/sys-root/mingw/`. All packages are compiled with that prefix (and this is not DESTDIR, but really where they are placed by `make install`), and any custom paths you provide must according to that prefix. So i.e. `mingw-enchant` (the 1.x package) is configured as

      ./configure --host=x86_64-w64-mingw32 --build=x86_64-redhat-linux-gnu --target=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --exec-prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --bindir=/usr/x86_64-w64-mingw32/sys-root/mingw/bin --sbindir=/usr/x86_64-w64-mingw32/sys-root/mingw/sbin --sysconfdir=/usr/x86_64-w64-mingw32/sys-root/mingw/etc --datadir=/usr/x86_64-w64-mingw32/sys-root/mingw/share --includedir=/usr/x86_64-w64-mingw32/sys-root/mingw/include --libdir=/usr/x86_64-w64-mingw32/sys-root/mingw/lib --libexecdir=/usr/x86_64-w64-mingw32/sys-root/mingw/libexec --localstatedir=/usr/x86_64-w64-mingw32/sys-root/mingw/var --sharedstatedir=/usr/x86_64-w64-mingw32/sys-root/mingw/com --mandir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/man --infodir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/info --with-hunspell-dir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/myspell --disable-static --enable-relocatable

which results in

      $ rpm -ql mingw64-enchant2
      /usr/x86_64-w64-mingw32/sys-root/mingw/bin/enchant-2.exe
      /usr/x86_64-w64-mingw32/sys-root/mingw/bin/enchant-lsmod-2.exe
      /usr/x86_64-w64-mingw32/sys-root/mingw/bin/libenchant-2.dll
      /usr/x86_64-w64-mingw32/sys-root/mingw/include/enchant-2
      /usr/x86_64-w64-mingw32/sys-root/mingw/include/enchant-2/enchant++.h
      /usr/x86_64-w64-mingw32/sys-root/mingw/include/enchant-2/enchant-provider.h
      /usr/x86_64-w64-mingw32/sys-root/mingw/include/enchant-2/enchant.h
      /usr/x86_64-w64-mingw32/sys-root/mingw/lib/enchant-2
      /usr/x86_64-w64-mingw32/sys-root/mingw/lib/enchant-2/enchant_hunspell.dll
      /usr/x86_64-w64-mingw32/sys-root/mingw/lib/enchant-2/enchant_hunspell.dll.a
      /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libenchant-2.dll.a
      /usr/x86_64-w64-mingw32/sys-root/mingw/lib/pkgconfig/enchant-2.pc
      /usr/x86_64-w64-mingw32/sys-root/mingw/share/enchant-2
      /usr/x86_64-w64-mingw32/sys-root/mingw/share/enchant-2/enchant.ordering

  notice in particular `--with-hunspell-dir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/myspell`

- When you deploy the program to the target system (i.e. Windows), you just copy the files you need below the prefix, and put them somewhere on your windows filesystem.  For example

        C:\PROGRAM FILES\GIMAGEREADER
        ├───bin
        │   ├───imageformats
        │   └───platforms
        ├───lib
        │   └───enchant
        └───share
            ├───doc
            │   └───gimagereader
            ├───enchant
            ├───icons
            │   └───hicolor
            ├───metainfo
            ├───myspell
            │   └───dicts
            ├───qt5
            ├───tessdata
            └───xml
                └───iso-codes

where the contents of `C:\PROGRAM FILES\GIMAGEREADER` are binaries coming from my mingw prefix on the host system.

I hope this explains the use-case.

For the record, I'm one of the main maintainers of mingw packages for Fedora.

**Comment by rrthomas** [comment]
This sounds like a use-case that isn't directly covered by the notion of relocation in gnulib, which covers relocating an app, not an entire installation. I must admit, I can't really tell whether it is or ought to be directly supported, but in any case, the place to ask is bug-gnulib@gnu.org.

As far as Enchant 2 goes, the idea is that relocation support is provided by gnulib's relocate module, and, as far as prefixes go, by autotools, and the maintainer shouldn't need to worry about or indeed understand this sort of problem, beyond implementing relocatable correctly.

I now have some feedback from the gnulib maintainers on how to implement the compiler settings properly so that they are picked up by the compilation of `relocatable.c`:

http://lists.gnu.org/archive/html/bug-gnulib/2017-12/msg00012.html

so I will do that.

**Comment by manisandro** [comment]
With the modifications posted above relocation works just fine, so it is not a problem of relocation in gnulib (in other words, the code to make it work is all there in gnulib relocation).

I think the only remaining issue is about the hunspell dir, which is an enchant issue whether it should or not be relocated. I see no harm in it being relocated to be honest.

(Just FWIW, the use case I posted above is by no means something fancy or exotic, it is standard practice when cross-compiling with linux mingw toolchains)

**Comment by rrthomas** [comment]
The problem _is_ with (the use of) gnulib, because `lib/Makefile.am` is also part of gnulib. So, there is no way to patch it (as you see, it is not in Enchant git). In the email I link to above, Bruno Haible shows how to modify the build system so that `relocatable.c` is built correctly.

The problem with relocating the hunspell directory is that it does not make sense in the normal use of relocation. Normally, it is Enchant (perhaps in some application) that is being relocated, and the directory passed to `--with-hunspell-dir` is a fixed system directory (not part of what is being relocated). 

I must admit I don't understand your use of prefix when as far as I can see it should be `DESTDIR`, but maybe that's just my ignorance about Mingw cross-compilation conventions. Again, I don't think I should have to understand this to maintain Enchant.

**Comment by manisandro** [comment]
Well but as the buildsystem is fixable to ensure the correct configuration of gnulib, as indicated in the email link above, I'd say the plan of action for that issue is clear.

I'll give it one more shot about destdir and prefix:

DESTDIR is essentially only there for packaging purposes. For any (say `deb` or `rpm` or whatever) package, packaging usually boils down to

    ./configure --prefix=<desired prefix, say /usr>
    make
    make install DESTDIR=<temporary dir>

and then the contents of `<temporary dir>` is tar'ed, zip'ed or whatever to obtain the desired package. This avoids you having to install the files inside the actual system prefix just for the sake of packaging. The files placed inside DESTDIR are however meant to be installed to the prefix which was specified. So DESTDIR isn't really used for tasks beyond packaging.

(You say that in your view `/usr/x86_64-w64-mingw32/sys-root/mingw/` should be the DESTDIR, but what should the prefix be then (which you *have* to pass to `configure`)? The destination location on Windows? But that's exactly what you don't know, hence the entire bother of relocating stuff.)

And about `hunspell-dir`: if you want to pass a fixed directory, you still can even if it is relocated. After all, what relocation does is look whether a path begins with the compile-time prefix, and if so, it replaces it with the runtime prefix. So i.e. with

    Compile time prefix: /usr/x86_64-w64-mingw32/sys-root/mingw/
    Runtime prefix: C:/Program Files/MyApp/

- If I set `hunspell-dir` to `/usr/x86_64-w64-mingw32/sys-root/mingw/share/myspell`, then it will be relocated to `C:/Program Files/MyApp/share/myspell` as I want, because `relocatable.c` notices that `hunspell-dir` begins with `/usr/x86_64-w64-mingw32/sys-root/mingw/share/myspell` and hence replaces that portion of the path with `C:/Program Files/MyApp/`.
- If I set `hunspell-dir` to `C:\Program Files\hunspell` (because I really want that fixed directory), it will still work, because `relocatable.c` will notice that that path does *not* begin with `/usr/x86_64-w64-mingw32/sys-root/mingw/share/myspell` and hence will leave it alone.

So again, there isn't really any downside in allowing `hunspell-dir` to be relocatable.

Note that I don't want to be annoying, and I could just patch the package downstream and call it a day. But I've been in the packaging business long enough and spent countless hours with all sorts of buildsystem issues to prefer speaking with upstream and seeing problems are understood and fixed at that level rather than having each package maintainer for every distro carrying their own slightly different downstream patch which have to be rebased every time an update comes along.

**Comment by rrthomas** [comment]
Thanks very much for your polite persistence. At the moment I'm trying to fix the gnulib side of things; as you say, it doesn't actually seem to require a change to gnulib code, but I think it will require a change to gnulib documentation, as the current documentation (including a bit that I wrote, because it was missing!) appears to be wrong. I want to document a standard method so that other maintainers in future can easily use gnulib to provide this functionality, with even less understanding than I am unfortunately having to develop!

As for `DESTDIR` vs prefix, in the example you give I would pass `--prefix=/mingw` and set `DESTDIR=/usr/x86_64-w64-mingw32/sys-root`. Then, mingw will supply the actual Windows directory via the setting in its `/etc/fstab`. This means that standard non-relocatable programs will also relocate. (I assume that is why the mingw `/etc/fstab` mechanism exists?)

The problem with calling `relocate` on the hunspell directory is: what happens if the compile-time prefix for the system hunspell is the same as the compile-time prefix for the application? Then it will be relocated, but it should not be. So for example, suppose I install hunspell at `/usr/local`. Then I build enchant with no `--prefix` setting (so it defaults to `/usr/local`), and then move it to, say, `/home/foo/myenchant`. When it runs, it will try to find hunspell dictionaries under `/home/foo/myenchant/share` rather than `/usr/local/share`, which will fail. Or am I missing something?

**Comment by manisandro** [comment]
I think you are confusing prefix of the package management system prefix vs installation prefix.

`<Drive>:\mingw` on windows is the location for the mingw-development tree under windows, i.e. where your compiler and all libraries get installed by the mingw package install tool (http://www.mingw.org/) which you use to develop your application. You will then deploy your application to say `C:\Program Files\MyApp`. The `/etc/fstab` you mention above is just an internal aspect of the mingw development tree. For the deployed application (i.e. as the end user will install), the mingw development tree plays no role anymore.

`/usr/x86_64-w64-mingw32/sys-root/mingw` on Linux is exactly the same as `<Drive>:\mingw` on Windows, i.e. it is the mingw-development tree under Linux. Once you deploy the application, the development tree will again play no role anymore. All you need to ensure is that all paths compiled into the binaries have a consistent prefix so that they can be relocated properly.


The example you make is correct, `/usr/local/share/` would get relocated to `/home/foo/myenchant/share`. But the case you mention is a case of partial relocation, i.e. you want some items to be relocated and some not, even if they are in the same prefix. I think it is fair to say that almost no-one will expect this, the entire point of prefixes is to specify a root underneath which the components interact and work together. The idea is that you relocated the full contents of a prefix, not just one part.

**Comment by rrthomas** [comment]
I think I begin to understand how mingw works. As far as I can see, it depends on relocation support in each package (except for programs that don't require access to other files, but that rules out e.g. gettext i18n).

I had another look at the relocatable documentation, and I had forgotten that it recommends building relocatable packages with `--prefix=/nonexistent`, so in fact there's no problem relocating the hunspell path, so I can do that. That should also be done for other similar paths in other providers.

So in fact, it seems that our requirements can both be fulfilled, even though the reasoning is different. (In particular, the point of relocatable is simply that you can copy the program files, e.g. from one user account to another; there's no requirement that they be in a separate tree from other programs. So the "partial relocation" you talk about is a perfectly supported and normal case.)

**Comment by manisandro** [comment]
Yes correct, each package is expected to contain it's own relocation logic. Qt packages will typically use [QCoreApplication::applicationDirPath()](http://doc.qt.io/qt-5/qcoreapplication.html#applicationDirPath), glib applications targeting win32 often use [g_win32_get_package_installation_directory_of_module](https://developer.gnome.org/glib/stable/glib-Windows-Compatibility-Functions.html#g-win32-get-package-installation-directory-of-module), and `gnulib` I suppose is the generic, agnostic way.

Ok yes, if you build with `--prefix=/nonexistent` your use case is indeed also covered. I hadn't though of that.

Anyway cool, so I think we've managed to find the solution for all these relocation problems!

**Comment by rrthomas** [comment]
Please can you let me know whether current git master is now suitable without patching? I think I've fixed everything…

**Comment by manisandro** [comment]
Looks good, tested on native Fedora and mingw-cross-compiled on Windows. Thanks! I take you are about to release version 2.2.0?

**Comment by rrthomas** [comment]
Indeed I am. Thanks for the confirmation.

**Comment by rrthomas** [comment]
Released with 2.2.0.

**Comment by Ede123** [comment]
Despite the amount of work invested here, I still can't seem to get relocation working with mingw-w64 (MSYS2 environment), see #198. Any idea?
