### ISSUE TITLE
list-dicts returns dictionaries, but they're unusable

### ISSUE THREAD

**Issue by LouisTrezzini** [rrthomas/enchant#289]
Hello,

I've installed enchant from source on CentOS 7, along with aspell support and dictionaries. 

Enchant doesn't seem to be able to load the dictionaries. I may have not installed everything properly, but it seems strange that `enchant-lsmod-2 -list-dicts` is still able to find the dictionaries.

Let me know if I can do anything to help solve the issue.

Thanks! 

### Logs

```bash
-bash-4.2$ ./configure --with-aspell-dir=/usr/lib64/aspell-0.60 && make
-bash-4.2$ sudo make install
-bash-4.2$ /usr/local/bin/enchant-lsmod-2 -list-dicts
en (aspell)
en_AU (aspell)
en_CA (aspell)
en_GB (aspell)
en_US (aspell)
es (aspell)
fr (aspell)
fr_CH (aspell)
fr_FR (aspell)
-bash-4.2$ /usr/local/bin/enchant-lsmod-2 -lang fr
No dictionary available for 'fr'
```

**Comment by rrthomas** [comment]
Thanks for this, indeed, this is not the behaviour I'd expect.

I've had a look at the code, and I can't see anywhere in particular that it might go wrong, but clearly it should not be listing dictionaries which it then can't find (unless of course something happened between those two invocations of `enchant-lsmod-2`!).

In this case, the problem seems to be between the `list_dicts` method and the `request_dict` method of the `aspell` provider.

I'll have a bit more of a dig when I have time. Are you up to recompiling with adding some debug `printf`s?

**Comment by LouisTrezzini** [comment]
Thanks for looking into it. I'm happy to recompile with some debug `printf`s, perhaps you can share a patch?

**Comment by rrthomas** [comment]
Please can you confirm which version you installed? I presume from git master? (I have discovered that the odd behaviour I found on my own system seems to have been fixed recently.)

**Comment by LouisTrezzini** [comment]
No, I was using the `enchant-2.3.1` tarball. I just tried with `master` and I run into the same issue.

**Comment by rrthomas** [comment]
Thanks; indeed, there are no significant changes since 2.3.1. I am making a debug branch now.

**Comment by rrthomas** [comment]
I have pushed a branch `debug-issue-289`; please can you check it out, @LouisTrezzini, build it with

```
./configure --enable-relocatable CFLAGS="-O2 -g3 -DDEBUG"
```

and then re-run your commands and paste the output here?

**Comment by LouisTrezzini** [comment]
Thanks!

I couldn't find the branch here so I assumed it was on your fork? However, the output is the same as above

**Comment by rrthomas** [comment]
Sorry, @LouisTrezzini, indeed the branch is on my fork. Sounds like you may have used `master`, though? Otherwise, you should get extra output.

**Comment by LouisTrezzini** [comment]
I'm definitely on `debug-issue-289`. I only see https://github.com/rrthomas/enchant/commit/4c952c46f8766a736bdce29163501f85a7000159, which doesn't do anything? Perhaps you forgot to push a commit?
Thanks again for your help!

**Comment by rrthomas** [comment]
Apologies @LouisTrezzini, I did indeed forget to add some files to that commit. I've now repushed the branch; you should find some actual debug statements now!

**Comment by LouisTrezzini** [comment]
No worries. Here's the output:

```
-bash-4.2$ /usr/local/bin/enchant-lsmod-2 -list-dicts
enchant_broker_list_dicts
provider: aspell
aspell_provider_list_dicts: 58 dicts
dict: de  60
dict: de_AT  60
dict: de_CH  60
dict: de_DE  60
dict: en  60
dict: en variant_0 60
dict: en variant_1 60
dict: en variant_2 60
dict: en w_accents 60
dict: en wo_accents 60
dict: en_AU  60
dict: en_AU variant_0 60
dict: en_AU variant_1 60
dict: en_AU w_accents 60
dict: en_AU wo_accents 60
dict: en_CA  60
dict: en_CA variant_0 60
dict: en_CA variant_1 60
dict: en_CA w_accents 60
dict: en_CA wo_accents 60
dict: en_GB  60
dict: en_GB ise 60
dict: en_GB ise-w_accents 60
dict: en_GB ise-wo_accents 60
dict: en_GB ize 60
dict: en_GB ize-w_accents 60
dict: en_GB ize-wo_accents 60
dict: en_GB variant_0 60
dict: en_GB variant_1 60
dict: en_GB w_accents 60
dict: en_GB wo_accents 60
dict: en_US  60
dict: en_US variant_0 60
dict: en_US variant_1 60
dict: en_US w_accents 60
dict: en_US wo_accents 60
dict: es  60
dict: fr  40
dict: fr  60
dict: fr  60
dict: fr  80
dict: fr lrg 60
dict: fr med 60
dict: fr sml 60
dict: fr_CH  40
dict: fr_CH  60
dict: fr_CH  60
dict: fr_CH  80
dict: fr_CH lrg 60
dict: fr_CH med 60
dict: fr_CH sml 60
dict: fr_FR  40
dict: fr_FR  60
dict: fr_FR  60
dict: fr_FR  80
dict: fr_FR lrg 60
dict: fr_FR med 60
dict: fr_FR sml 60
58 dicts
dict: de
dict: de_AT
dict: de_CH
dict: de_DE
dict: en
dict: en
dict: en
dict: en
dict: en
dict: en
dict: en_AU
dict: en_AU
dict: en_AU
dict: en_AU
dict: en_AU
dict: en_CA
dict: en_CA
dict: en_CA
dict: en_CA
dict: en_CA
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_US
dict: en_US
dict: en_US
dict: en_US
dict: en_US
dict: es
dict: fr
dict: fr
dict: fr
dict: fr
dict: fr
dict: fr
dict: fr
dict: fr_CH
dict: fr_CH
dict: fr_CH
dict: fr_CH
dict: fr_CH
dict: fr_CH
dict: fr_CH
dict: fr_FR
dict: fr_FR
dict: fr_FR
dict: fr_FR
dict: fr_FR
dict: fr_FR
dict: fr_FR
de (aspell)
de_AT (aspell)
de_CH (aspell)
de_DE (aspell)
en (aspell)
en_AU (aspell)
en_CA (aspell)
en_GB (aspell)
en_US (aspell)
es (aspell)
fr (aspell)
fr_CH (aspell)
fr_FR (aspell)
-bash-4.2$ /usr/local/bin/enchant-lsmod-2 -lang fr
_enchant_broker_request_dict: fr
trying provider aspell
_enchant_broker_request_dict: fr
trying provider aspell
No dictionary available for 'fr'
```

**Comment by rrthomas** [comment]
Thanks; I'll add some more debugging…

**Comment by rrthomas** [comment]
I've added some debugging to the aspell provider to output the aspell error message when it fails to get a dictionary; could you try the same thing again with the updated code, please?

**Comment by LouisTrezzini** [comment]
Thanks so much for helping! 

Here are the logs:

```
-bash-4.2$ /usr/local/bin/enchant-lsmod-2 -list-dicts
enchant_broker_list_dicts
provider: aspell
aspell_provider_list_dicts: 58 dicts
dict: de  60
dict: de_AT  60
dict: de_CH  60
dict: de_DE  60
dict: en  60
dict: en variant_0 60
dict: en variant_1 60
dict: en variant_2 60
dict: en w_accents 60
dict: en wo_accents 60
dict: en_AU  60
dict: en_AU variant_0 60
dict: en_AU variant_1 60
dict: en_AU w_accents 60
dict: en_AU wo_accents 60
dict: en_CA  60
dict: en_CA variant_0 60
dict: en_CA variant_1 60
dict: en_CA w_accents 60
dict: en_CA wo_accents 60
dict: en_GB  60
dict: en_GB ise 60
dict: en_GB ise-w_accents 60
dict: en_GB ise-wo_accents 60
dict: en_GB ize 60
dict: en_GB ize-w_accents 60
dict: en_GB ize-wo_accents 60
dict: en_GB variant_0 60
dict: en_GB variant_1 60
dict: en_GB w_accents 60
dict: en_GB wo_accents 60
dict: en_US  60
dict: en_US variant_0 60
dict: en_US variant_1 60
dict: en_US w_accents 60
dict: en_US wo_accents 60
dict: es  60
dict: fr  40
dict: fr  60
dict: fr  60
dict: fr  80
dict: fr lrg 60
dict: fr med 60
dict: fr sml 60
dict: fr_CH  40
dict: fr_CH  60
dict: fr_CH  60
dict: fr_CH  80
dict: fr_CH lrg 60
dict: fr_CH med 60
dict: fr_CH sml 60
dict: fr_FR  40
dict: fr_FR  60
dict: fr_FR  60
dict: fr_FR  80
dict: fr_FR lrg 60
dict: fr_FR med 60
dict: fr_FR sml 60
58 dicts
dict: de
dict: de_AT
dict: de_CH
dict: de_DE
dict: en
dict: en
dict: en
dict: en
dict: en
dict: en
dict: en_AU
dict: en_AU
dict: en_AU
dict: en_AU
dict: en_AU
dict: en_CA
dict: en_CA
dict: en_CA
dict: en_CA
dict: en_CA
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_GB
dict: en_US
dict: en_US
dict: en_US
dict: en_US
dict: en_US
dict: es
dict: fr
dict: fr
dict: fr
dict: fr
dict: fr
dict: fr
dict: fr
dict: fr_CH
dict: fr_CH
dict: fr_CH
dict: fr_CH
dict: fr_CH
dict: fr_CH
dict: fr_CH
dict: fr_FR
dict: fr_FR
dict: fr_FR
dict: fr_FR
dict: fr_FR
dict: fr_FR
dict: fr_FR
de (aspell)
de_AT (aspell)
de_CH (aspell)
de_DE (aspell)
en (aspell)
en_AU (aspell)
en_CA (aspell)
en_GB (aspell)
en_US (aspell)
es (aspell)
fr (aspell)
fr_CH (aspell)
fr_FR (aspell)
-bash-4.2$ /usr/local/bin/enchant-lsmod-2 -lang fr
_enchant_broker_request_dict: fr
trying provider aspell
aspell error 1: The file "/usr/lib64/aspell-0.60/iso-8859-1.cset" can not be opened for reading.
_enchant_broker_request_dict: fr
trying provider aspell
aspell error 1: The file "/usr/lib64/aspell-0.60/iso-8859-1.cset" can not be opened for reading.
No dictionary available for 'fr'
-bash-4.2$ ll /usr/lib64/aspell-0.60
total 34804
-rw-r--r--. 1 root root       75 Jan 16  2014 american.alias
-rw-r--r--. 1 root root       85 Jan 16  2014 american-variant_0.alias
-rw-r--r--. 1 root root       85 Jan 16  2014 american-variant_1.alias
-rw-r--r--. 1 root root       85 Jan 16  2014 american-w_accents.alias
-rw-r--r--. 1 root root       86 Jan 16  2014 american-wo_accents.alias
-rw-r--r--. 1  501  501       75 Dec  7  2020 australian.alias
-rw-r--r--. 1  501  501       85 Dec  7  2020 australian-variant_0.alias
-rw-r--r--. 1  501  501       85 Dec  7  2020 australian-variant_1.alias
-rw-r--r--. 1  501  501       85 Dec  7  2020 australian-w_accents.alias
-rw-r--r--. 1  501  501       86 Dec  7  2020 australian-wo_accents.alias
-rw-r--r--. 1 root root       75 Jan 16  2014 british.alias
-rw-r--r--. 1 root root       79 Jan 16  2014 british-ise.alias
-rw-r--r--. 1 root root       89 Jan 16  2014 british-ise-w_accents.alias
-rw-r--r--. 1 root root       90 Jan 16  2014 british-ise-wo_accents.alias
-rw-r--r--. 1 root root       79 Jan 16  2014 british-ize.alias
-rw-r--r--. 1 root root       89 Jan 16  2014 british-ize-w_accents.alias
-rw-r--r--. 1 root root       90 Jan 16  2014 british-ize-wo_accents.alias
-rw-r--r--. 1 root root       85 Jan 16  2014 british-variant_0.alias
-rw-r--r--. 1 root root       85 Jan 16  2014 british-variant_1.alias
-rw-r--r--. 1 root root       85 Jan 16  2014 british-w_accents.alias
-rw-r--r--. 1 root root       86 Jan 16  2014 british-wo_accents.alias
-rw-r--r--. 1 root root       75 Jan 16  2014 canadian.alias
-rw-r--r--. 1 root root       85 Jan 16  2014 canadian-variant_0.alias
-rw-r--r--. 1 root root       85 Jan 16  2014 canadian-variant_1.alias
-rw-r--r--. 1 root root       85 Jan 16  2014 canadian-w_accents.alias
-rw-r--r--. 1 root root       86 Jan 16  2014 canadian-wo_accents.alias
-rw-r--r--. 1 root root       72 Apr 16  2016 castellano.alias
-rwxr-xr-x. 1  501  501     2477 Dec  7  2020 configure
-rw-r--r--. 1  501  501    12193 Dec  7  2020 Copyright
-rw-r--r--. 1 root root    14042 Apr 16  2016 de_affix.dat
-rw-r--r--. 1 root root       96 Apr 16  2016 de_AT.multi
-rw-r--r--. 1 root root   664752 Apr 16  2016 de_AT-only.rws
-rw-r--r--. 1 root root       96 Apr 16  2016 de_CH.multi
-rw-r--r--. 1 root root   655248 Apr 16  2016 de_CH-only.rws
-rw-r--r--. 1 root root  9358000 Apr 16  2016 de-common.rws
-rw-r--r--. 1 root root      115 Apr 16  2016 de.dat
-rw-r--r--. 1 root root       96 Apr 16  2016 de_DE.multi
-rw-r--r--. 1 root root   649648 Apr 16  2016 de_DE-only.rws
-rw-r--r--. 1 root root       75 Apr 16  2016 de.multi
-rw-r--r--. 1 root root    12479 Apr 16  2016 de_phonet.dat
-rw-r--r--. 1 root root       75 Apr 16  2016 deutsch.alias
drwxr-xr-x. 2  501  501       60 Dec  7  2020 doc
-rw-r--r--. 1 root root     4675 Jan 16  2014 en_affix.dat
-rw-r--r--. 1  501  501       86 Dec  7  2020 en_AU.multi
-rw-r--r--. 1  501  501     5166 Dec  7  2020 en_AU-variant_0.cwl
-rw-r--r--. 1  501  501       83 Dec  7  2020 en_AU-variant_0.multi
-rw-r--r--. 1  501  501    13261 Dec  7  2020 en_AU-variant_1.cwl
-rw-r--r--. 1  501  501       83 Dec  7  2020 en_AU-variant_1.multi
-rw-r--r--. 1  501  501      106 Dec  7  2020 en_AU-w_accents.multi
-rw-r--r--. 1  501  501    16194 Dec  7  2020 en_AU-w_accents-only.cwl
-rw-r--r--. 1  501  501      107 Dec  7  2020 en_AU-wo_accents.multi
-rw-r--r--. 1  501  501    16157 Dec  7  2020 en_AU-wo_accents-only.cwl
-rw-r--r--. 1 root root       86 Jan 16  2014 en_CA.multi
-rw-r--r--. 1  501  501     6440 Dec  7  2020 en_CA-variant_0.cwl
-rw-r--r--. 1 root root       83 Jan 16  2014 en_CA-variant_0.multi
-rw-r--r--. 1 root root    37328 Jan 16  2014 en_CA-variant_0.rws
-rw-r--r--. 1  501  501    13714 Dec  7  2020 en_CA-variant_1.cwl
-rw-r--r--. 1 root root       83 Jan 16  2014 en_CA-variant_1.multi
-rw-r--r--. 1 root root    73344 Jan 16  2014 en_CA-variant_1.rws
-rw-r--r--. 1 root root      106 Jan 16  2014 en_CA-w_accents.multi
-rw-r--r--. 1  501  501    14043 Dec  7  2020 en_CA-w_accents-only.cwl
-rw-r--r--. 1 root root    91760 Jan 16  2014 en_CA-w_accents-only.rws
-rw-r--r--. 1 root root      107 Jan 16  2014 en_CA-wo_accents.multi
-rw-r--r--. 1  501  501    14010 Dec  7  2020 en_CA-wo_accents-only.cwl
-rw-r--r--. 1 root root    91760 Jan 16  2014 en_CA-wo_accents-only.rws
-rw-r--r--. 1  501  501   395015 Dec  7  2020 en-common.cwl
-rw-r--r--. 1 root root  2334032 Jan 16  2014 en-common.rws
-rw-r--r--. 1 root root       88 Jan 16  2014 en.dat
-rw-r--r--. 1 root root       90 Jan 16  2014 en_GB-ise.multi
-rw-r--r--. 1 root root      110 Jan 16  2014 en_GB-ise-w_accents.multi
-rw-r--r--. 1  501  501    14130 Dec  7  2020 en_GB-ise-w_accents-only.cwl
-rw-r--r--. 1 root root    92560 Jan 16  2014 en_GB-ise-w_accents-only.rws
-rw-r--r--. 1 root root      111 Jan 16  2014 en_GB-ise-wo_accents.multi
-rw-r--r--. 1  501  501    14098 Dec  7  2020 en_GB-ise-wo_accents-only.cwl
-rw-r--r--. 1 root root    92560 Jan 16  2014 en_GB-ise-wo_accents-only.rws
-rw-r--r--. 1 root root       90 Jan 16  2014 en_GB-ize.multi
-rw-r--r--. 1 root root      110 Jan 16  2014 en_GB-ize-w_accents.multi
-rw-r--r--. 1  501  501    13990 Dec  7  2020 en_GB-ize-w_accents-only.cwl
-rw-r--r--. 1 root root    92176 Jan 16  2014 en_GB-ize-w_accents-only.rws
-rw-r--r--. 1 root root      111 Jan 16  2014 en_GB-ize-wo_accents.multi
-rw-r--r--. 1  501  501    13958 Dec  7  2020 en_GB-ize-wo_accents-only.cwl
-rw-r--r--. 1 root root    92176 Jan 16  2014 en_GB-ize-wo_accents-only.rws
-rw-r--r--. 1 root root       90 Jan 16  2014 en_GB.multi
-rw-r--r--. 1  501  501     4714 Dec  7  2020 en_GB-variant_0.cwl
-rw-r--r--. 1 root root       83 Jan 16  2014 en_GB-variant_0.multi
-rw-r--r--. 1 root root    26256 Jan 16  2014 en_GB-variant_0.rws
-rw-r--r--. 1  501  501    11929 Dec  7  2020 en_GB-variant_1.cwl
-rw-r--r--. 1 root root       83 Jan 16  2014 en_GB-variant_1.multi
-rw-r--r--. 1 root root    62784 Jan 16  2014 en_GB-variant_1.rws
-rw-r--r--. 1 root root       89 Jan 16  2014 en_GB-w_accents.multi
-rw-r--r--. 1 root root       90 Jan 16  2014 en_GB-wo_accents.multi
-rw-r--r--. 1 root root       72 Jan 16  2014 english.alias
-rw-r--r--. 1 root root       82 Jan 16  2014 english-variant_0.alias
-rw-r--r--. 1 root root       82 Jan 16  2014 english-variant_1.alias
-rw-r--r--. 1 root root       82 Jan 16  2014 english-variant_2.alias
-rw-r--r--. 1 root root       82 Jan 16  2014 english-w_accents.alias
-rw-r--r--. 1 root root       83 Jan 16  2014 english-wo_accents.alias
-rw-r--r--. 1 root root       83 Jan 16  2014 en.multi
-rw-r--r--. 1 root root     7273 Jan 16  2014 en_phonet.dat
-rw-r--r--. 1 root root       86 Jan 16  2014 en_US.multi
-rw-r--r--. 1 root root       82 Jan 16  2014 en_US-variant_0.multi
-rw-r--r--. 1 root root       82 Jan 16  2014 en_US-variant_1.multi
-rw-r--r--. 1 root root      106 Jan 16  2014 en_US-w_accents.multi
-rw-r--r--. 1  501  501    15586 Dec  7  2020 en_US-w_accents-only.cwl
-rw-r--r--. 1 root root    90576 Jan 16  2014 en_US-w_accents-only.rws
-rw-r--r--. 1 root root      107 Jan 16  2014 en_US-wo_accents.multi
-rw-r--r--. 1  501  501    15539 Dec  7  2020 en_US-wo_accents-only.cwl
-rw-r--r--. 1 root root    90576 Jan 16  2014 en_US-wo_accents-only.rws
-rw-r--r--. 1  501  501     6513 Dec  7  2020 en-variant_0.cwl
-rw-r--r--. 1 root root       80 Jan 16  2014 en-variant_0.multi
-rw-r--r--. 1 root root    34736 Jan 16  2014 en-variant_0.rws
-rw-r--r--. 1  501  501    16665 Dec  7  2020 en-variant_1.cwl
-rw-r--r--. 1 root root       80 Jan 16  2014 en-variant_1.multi
-rw-r--r--. 1 root root    87248 Jan 16  2014 en-variant_1.rws
-rw-r--r--. 1  501  501    18119 Dec  7  2020 en-variant_2.cwl
-rw-r--r--. 1 root root       80 Jan 16  2014 en-variant_2.multi
-rw-r--r--. 1 root root    95808 Jan 16  2014 en-variant_2.rws
-rw-r--r--. 1 root root      103 Jan 16  2014 en-w_accents.multi
-rw-r--r--. 1  501  501    27512 Dec  7  2020 en-w_accents-only.cwl
-rw-r--r--. 1 root root   108416 Jan 16  2014 en-w_accents-only.rws
-rw-r--r--. 1 root root      104 Jan 16  2014 en-wo_accents.multi
-rw-r--r--. 1  501  501    27460 Dec  7  2020 en-wo_accents-only.cwl
-rw-r--r--. 1 root root   108416 Jan 16  2014 en-wo_accents-only.rws
-rw-r--r--. 1 root root   186395 Apr 16  2016 es_affix.dat
-rw-r--r--. 1 root root      132 Apr 16  2016 es.dat
-rw-r--r--. 1 root root       70 Apr 16  2016 es.multi
-rw-r--r--. 1 root root       72 Apr 16  2016 espanol.alias
-rw-r--r--. 1 root root  1279184 Apr 16  2016 es.rws
-rw-r--r--. 1 root root       78 Apr 16  2016 fr-40.multi
-rw-r--r--. 1 root root  5826736 Apr 16  2016 fr-40-only.rws
-rw-r--r--. 1 root root       78 Apr 16  2016 fr-60.multi
-rw-r--r--. 1 root root 11590736 Apr 16  2016 fr-60-only.rws
-rw-r--r--. 1 root root       78 Apr 16  2016 fr-80.multi
-rw-r--r--. 1 root root   334880 Apr 16  2016 fr-80-only.rws
-rw-r--r--. 1 root root       78 Apr 16  2016 francais-40.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 francais-60.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 francais-80.alias
-rw-r--r--. 1 root root       75 Apr 16  2016 francais.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 francais-lrg.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 francais-med.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 francais-sml.alias
-rw-r--r--. 1 root root       97 Apr 16  2016 fr_CH-40.multi
-rw-r--r--. 1 root root      116 Apr 16  2016 fr_CH-60.multi
-rw-r--r--. 1 root root      135 Apr 16  2016 fr_CH-80.multi
-rw-r--r--. 1 root root       78 Apr 16  2016 fr_CH-lrg.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 fr_CH-med.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 fr_CH.multi
-rw-r--r--. 1 root root     2816 Apr 16  2016 fr_CH-only.rws
-rw-r--r--. 1 root root       78 Apr 16  2016 fr_CH-sml.alias
-rw-r--r--. 1 root root      126 Apr 16  2016 fr.dat
-rw-r--r--. 1 root root       78 Apr 16  2016 french-40.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 french-60.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 french-80.alias
-rw-r--r--. 1 root root       75 Apr 16  2016 french.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 french-lrg.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 french-med.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 french-sml.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 fr_FR-40.multi
-rw-r--r--. 1 root root       97 Apr 16  2016 fr_FR-60.multi
-rw-r--r--. 1 root root      116 Apr 16  2016 fr_FR-80.multi
-rw-r--r--. 1 root root       78 Apr 16  2016 fr_FR-lrg.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 fr_FR-med.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 fr_FR.multi
-rw-r--r--. 1 root root       78 Apr 16  2016 fr_FR-sml.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 fr-lrg.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 fr-med.alias
-rw-r--r--. 1 root root       75 Apr 16  2016 fr.multi
-rw-r--r--. 1 root root     2931 Apr 16  2016 fr_phonet.dat
-rw-r--r--. 1 root root       78 Apr 16  2016 fr-sml.alias
-rw-r--r--. 1 root root       75 Apr 16  2016 german.alias
-rw-r--r--. 1  501  501     2075 Dec  7  2020 info
-rw-r--r--. 1  501  501     5165 Dec  7  2020 Makefile.pre
-rw-r--r--. 1  501  501     6377 Dec  7  2020 README
-rw-r--r--. 1  501  501     6376 Dec  7  2020 README.iso
-rw-r--r--. 1 root root       72 Apr 16  2016 spanish.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 suisse-40.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 suisse-60.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 suisse-80.alias
-rw-r--r--. 1 root root       75 Apr 16  2016 suisse.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 suisse-lrg.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 suisse-med.alias
-rw-r--r--. 1 root root       78 Apr 16  2016 suisse-sml.alias
-rw-r--r--. 1 root root       75 Apr 16  2016 swiss.alias
```

It seems like the `/usr/lib64/aspell-0.60/iso-8859-1.cset` is missing for some reason. I force re-installed the `aspell` package and now it works... 😞

**Comment by rrthomas** [comment]
Thanks very much! I will look into whether I can sensibly report an error in this sort of case, as that would have made the problem obvious to you from the beginning.

**Comment by rrthomas** [comment]
I have pushed a fix to my master branch, which I've tested; I'd be grateful if you could test it too. When I remove the relevant encoding file for an aspell dictionary that has no substitute in another provider (for my test, I used `aspell-nr`), I get:

```
$ enchant-lsmod-2 -lang nr
No dictionary available for 'nr': The file "/usr/lib/aspell/iso-8859-1.cset" can not be opened for reading.
```

**Comment by LouisTrezzini** [comment]
Works great, many thanks!

```
-bash-4.2$ /usr/local/bin/enchant-lsmod-2 -lang de
No dictionary available for 'de': The file "/usr/lib64/aspell-0.60/iso-8859-1.cset" can not be opened for reading.
-bash-4.2$ poetry run python
Python 3.7.2 (default, Jul 17 2019, 12:01:55)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enchant
>>> enchant.request_dict('en_US')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/lib/jenkins/.venv/lib/python3.7/site-packages/enchant/__init__.py", line 272, in request_dict
    return Dict(tag, self)
  File "/var/lib/jenkins/.venv/lib/python3.7/site-packages/enchant/__init__.py", line 542, in __init__
    super().__init__()
  File "/var/lib/jenkins/.venv/lib/python3.7/site-packages/enchant/__init__.py", line 144, in __init__
    self._init_this()
  File "/var/lib/jenkins/.venv/lib/python3.7/site-packages/enchant/__init__.py", line 549, in _init_this
    this = self._broker._request_dict_data(self.tag)
  File "/var/lib/jenkins/.venv/lib/python3.7/site-packages/enchant/__init__.py", line 287, in _request_dict_data
    self._raise_error(e_str % (tag,), DictNotFoundError)
  File "/var/lib/jenkins/.venv/lib/python3.7/site-packages/enchant/__init__.py", line 234, in _raise_error
    raise eclass(err.decode())
enchant.errors.DictNotFoundError: The file "/usr/lib64/aspell-0.60/iso-8859-1.cset" can not be opened for reading.
>>>
```

**Comment by rrthomas** [comment]
Thanks, I'll make a new release shortly.
