### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by rrthomas** [rrthomas/enchant#37]
The tests under unittests do not currently run (in particular, they have some Windows-specific dependencies).

I have done some work on this, available in my [fix-unittests branch](/rrthomas/enchant/tree/fix-unittests).

However, currently I can't work out how the tests are supposed to be run. The top-level `main.cpp` contains no tests, and no other test file seems to refer to it.

**Comment by rrthomas** [comment]
@hfiguiere any ideas on this? I had a look at the documentation for UnitTest++, but it didn't enlighten me: it seems to suggest a test program has a main function, but in the unittests directory, only `main.cpp` does.

**Comment by hfiguiere** [comment]
I see many problems:

1. configure doesn't even check properly for the library, the makefile doesn't run the test properly and UnitTest++ is not included properly.
2. The test files need to be build. They are not.
3. All these test were designed to run on Windows. Which make 2. harder.

I have a patch for 1.

**Comment by hfiguiere** [comment]
1. is fixed by commit hfiguiere/enchant@3553507

**Comment by rrthomas** [comment]
OK, I found your branch, that wasn't at all obvious. I can't see it mentioned anywhere in the commit! (The URL for the commit is under `/AbiWord/enchant`, not `hfiguiere/enchant`.)

**Comment by hfiguiere** [comment]
(fixed the link)

**Comment by hfiguiere** [comment]
it is your branch, but rebased so that I could build it.

**Comment by rrthomas** [comment]
Thanks, the problem I had was mainly with github, which doesn't seem to show that the commit is on a branch of yours. I'll look into it later.

**Comment by rrthomas** [comment]
I've made a couple of comments on your commit where things don't seem right, and I've rebased my fix-unittests branch, and added those changes of yours that I didn't have problems with.

The basic problem remains that I don't know how the tests are supposed to be built; if you could shed some light on that, that would be great.

**Comment by rrthomas** [comment]
I've now updated my `fix-unittests` branch so that it builds one more test (there is a `main.cpp` in `enchant_providers`), and I think that may contain the clues I need to get more tests to run. I'll dig a bit further.

**Comment by hfiguiere** [comment]
My branch had many tests built. All you need is to add them to _SOURCES

**Comment by rrthomas** [comment]
Yes, I finally realised this, and felt a bit stupid. I will see if I can just cherry-pick your commits to my branch; after that I can look into `unittest++` detection.

**Comment by rrthomas** [comment]
I cherry-picked your commits to my branch, which I think can now be treated as a suitable base for forking, since it's fully up to date with `AbiWord/enchant/master`.

Obviously a lot of the unit tests currently fail. I have not tried to investigate yet, but it looks like a lot of the failures are because a dictionary could not be opened, so should be simple to fix.

Also, the `enchant_providers` tests are not yet being run properly: the `main` program in that directory needs to be given the available providers on the command line.

Finally, I looked into the pkgconfig problem. As you said, the `.pc` file supplied by libunittest++ is new since version 1.4. I filed an issue asking for guidance: unittest-cpp/unittest-cpp#45.

For the present we'll clearly have to deal with existing releases, so I guess we need to check for the Debian package, then for the UnitTest++, and in one case set a variable, so we can use an `#ifdef` to select the correct include path.

**Comment by hfiguiere** [comment]
I have a patch of the .pc file. Testing it right now.

**Comment by hfiguiere** [comment]
My branch now build completely on travis, be it with the outdated unittest and pkg-config found in Ubuntu than with the up to date Brew package on macOS.

**Comment by rrthomas** [comment]
That's great, thanks. I've manually cherry-picked the changes to my branch. Now just the small matter of 226 out of 405 tests failing!

**Comment by rrthomas** [comment]
I have copied code from `tests/Makefile.am` to `unittests/Makefile.am` to set `AM_TESTS_ENVIRONMENT` so that the tests can find the provider modules, and now the tests hang, apparently waiting for a lock in libc's malloc.

**Comment by rrthomas** [comment]
Upon investigation, the tests always use the language tag `qaa`. This seems to be set up to be provided by a mock provider, so the problem is that the mock provider (in `mock_provider`) is not build as a provider module. Trying that now.

**Comment by rrthomas** [comment]
`mock_provider` is now built properly, and it is now loaded by the test program, but the call to `enchant_broker_request_dict` for a dictionary for language `qaa` still fails.

I think this comes down to needing to fill in the section marked `// What to do?` at line 153 of `EnchantBrokerTestFixture.h`, as without this the mock provider is not set up to do anything useful.

**Comment by rrthomas** [comment]
I've implemented mock provider shared library loading using `dlopen`. At the moment, the `.so` must be manually copied from `unittests/mock_providers/.libs` to `unittests`.

The mock provider can now be loaded, but trying to get a dictionary for language `qaa` still fails. Not sure why yet.

**Comment by rrthomas** [comment]
I have made some progress: the same manual copy is needed as above, but the mock provider is now loaded, and I'm down to 36 out of 405 tests failing.

**Comment by rrthomas** [comment]
Only 18^W10 failing tests left!

**Comment by rrthomas** [comment]
Progress report: to understand the providers test failures I had to dive briefly into `dlopen` internals, sigh. Problem now understood and on the way to being fixed.

**Comment by rrthomas** [comment]
5 failing tests left.

**Comment by rrthomas** [comment]
Some of the remaining tests contain false assumptions, so there will be a few fixes. Now down to just 2 failures!

**Comment by rrthomas** [comment]
All failures fixed! There is one I am not sure about, I will give details in my pull request.

Travis is passing on Linux, but the build is timing out on macOS. I have access to a Mac, and can reproduce the problem there (the test appears to busy-hang), so am investigating.

However, I have first to get the provider unit tests running properly.

**Comment by rrthomas** [comment]
After some wrestling with debugging on the Mac (not what I'm used to, and various bits of system security get in the way), I tried installing unittest-cpp version 1.6.1, as brew currently installs 2.0.0 (also having installed it on my Ubuntu system and confirmed that the tests still work), but that didn't fix my problems.

That's good news, because it looks like it doesn't matter whether we build with unittest 1.4 (as I was using before on Ubuntu), 1.6 (as I am now using) or 2.0 (as I was using before on the Mac).

I think I've now found where the hang is (in libiconv, when converting a test string); but I still don't know yet why it is a problem. Time to stop for tonight!

**Comment by rrthomas** [comment]
There appears to be a bug in the Mac's libiconv (a `wchar_t` to `utf-8` conversion is just looping in the library). However, the `Convert` methods can be made much simpler by using C++ 11's `codecvt`.

This means that C++11 is required. However, it is available in GCC 5 and later, and hence on most current systems (e.g. Ubuntu LTS 14.04 or later; in a few months, that will be the earliest supported LTS). If this is a problem, C++11 could be required just for the tests.

Meanwhile, Travis is not running Mac builds at the moment, though I was getting good results earlier today, and I thought I only had one test to fix. I will have to see if that is right when the latest Mac builds finally complete!

Meanwhile, I started building the tests in `enchant_providers`. These pass fine.

**Comment by rrthomas** [comment]
I got an error message from Travis saying that XCode 7.2 was retired in November, so have updated to 7.3. This does not run on macOS 10.10, but perhaps it can still build for 10.10? (If not, there's not much point testing with it, since XCode 8.2 works on 10.11.)

**Comment by rrthomas** [comment]
Travis is having trouble with its Mac images.

I have tested the current fix-unittest branch on a Mac, and it is working fine, so I'll go ahead and prepare a PR; hopefully the Travis Mac images will be back up soon.

**Comment by rrthomas** [comment]
See PR #61.
